### PR TITLE
enhancement #85

### PR DESCRIPTION
**Pull request by dbrakenhoff**
Addresses #85:
- add discharge_per_linesink method
- assign solution parameters to member linesinks
- add assertion test in test_linesink_discharge notebook

Each of these should now work:
```python
ml = timml.ModelMaq(...)
hls = timml.HeadLineSinkString(...)
ml.solve()

Qtot = hls.discharge()  # total discharge per layer
Qls1 = hls.discharge_per_linesink()  # discharge per member linesink per layer, Qls1 is shape (nlay, nls)
Qls2 = [ls.discharge() for ls in ls.lslist]  # discharge per member linesink per layer, list of len(nls)
```

### CODE REVIEW

**Comment by dbrakenhoff** [comment]
@mbakker7, could you check this? Was there a reason not to set the parameters on the member linesinks...?

**Comment by mbakker7** [comment]
Just curious. What is wrong with 
```
if (layer in self.layers)
```

**Comment by dbrakenhoff** [comment]
The contour plot is passing on all layers, so layer=[0, 1, 2] and the well
element (self) has layers [0, 1]. If the element has just one layer it
works fine, but not with more layers.

Numpy doesn't like an unmatched elementwise comparison anymore apparently.

**Review by mbakker7 — APPROVED** [review]
Looks good.

**Pull request merged**
