### PR TITLE
Use pytest to run tests on notebooks and use travis-ci to test build for linux and osx

### PR DESCRIPTION
**Pull request by jentjr**
Mark,

I created a tests folder and slightly modified the [test_notebooks.py file from flopy](https://github.com/modflowpy/flopy/blob/develop/autotest/autotest_notebooks.py) to test all the notebooks, and created `.travis.yml` and `.appveyor.yml` to test builds for linux, osx and windows. The builds are successful for Python 3.5 and 3.6 on linux and macosx. I've tried several different ways (that's why there are so many commits) to get the windows build to run, but so far have been unsuccessful. The error from the appveyor build log is pasted below. Perhaps, you might know how to modify the appveyor configuration, or change the compiler flags? The compiler flags can be set now by operating system in `setup.py` 

`Traceback (most recent call last):`
`File "setup.py", line 42, in <module>`
  `setup_package()`
`File "setup.py", line 39, in setup_package`
   `setup(**metadata)`
`File "C:\Miniconda36-x64\lib\site-packages\numpy\distutils\core.py", line 169, in setup`
   `return old_setup(**new_attr)`
`File "C:\Miniconda36-x64\lib\distutils\core.py", line 148, in setup`
   `dist.run_commands()`
`File "C:\Miniconda36-x64\lib\distutils\dist.py", line 955, in run_commands`
   `self.run_command(cmd)`
`File "C:\Miniconda36-x64\lib\distutils\dist.py", line 974, in run_command`
   `cmd_obj.run()`
`File "C:\Miniconda36-x64\lib\site-packages\numpy\distutils\command\install.py", line 60, in run`
   `r = old_install.run(self)`
`File "C:\Miniconda36-x64\lib\distutils\command\install.py", line 545, in run`
   `self.run_command('build')`
`File "C:\Miniconda36-x64\lib\distutils\cmd.py", line 313, in run_command`
   `self.distribution.run_command(command)`
`File "C:\Miniconda36-x64\lib\distutils\dist.py", line 974, in run_command`
   `cmd_obj.run()`
`File "C:\Miniconda36-x64\lib\site-packages\numpy\distutils\command\build.py", line 47, in run`
   `old_build.run(self)`
`File "C:\Miniconda36-x64\lib\distutils\command\build.py", line 135, in run`
   `self.run_command(cmd_name)`
`File "C:\Miniconda36-x64\lib\distutils\cmd.py", line 313, in run_command`
   `self.distribution.run_command(command)`
`File "C:\Miniconda36-x64\lib\distutils\dist.py", line 974, in run_command`
   `cmd_obj.run()`
`File "C:\Miniconda36-x64\lib\site-packages\numpy\distutils\command\build_ext.py", line 117, in run`
   `force=self.force)`
`File "C:\Miniconda36-x64\lib\site-packages\numpy\distutils\ccompiler.py", line 733, in new_compiler`
   `compiler = klass(None, dry_run, force)`
`File "C:\Miniconda36-x64\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 69, in __init__`
   `dry_run, force)`
`File "C:\Miniconda36-x64\lib\distutils\cygwinccompiler.py", line 129, in __init__`
   `if self.ld_version >= "2.10.90":`
`TypeError: '>=' not supported between instances of 'NoneType' and 'str'`
`Command exited with code 1`

### CODE REVIEW

**Comment by mbakker7** [comment]
Justin,

Thanks for trying this out. I have always been surprised how little guidance there is to get a FORTRAN extension to work on Conda (and now on Travis). TimML is not doing anything fancy aside from the FORTRAN extension (which isn't reallly that fancy). 

I say you had lots of commits. Does it work now, or are you still trying.

Mark

**Comment by mbakker7** [comment]
Hey Justin,

Can you give a status update? Does it work now with Travis? Appveyor?

Thanks,

Mark

**Comment by mbakker7** [comment]
I use MING64 on my Windows machine. Have you tried that?

**Comment by jentjr** [comment]
Mark,

I was finally able to get all the builds passing on Travis for Linux and OSX and on Appveyor for Windows. The builds are setup for Python 3.5 and 3.6 in x86 and x64. I will have to figure out how to run the builds locally using a docker image so I don't have to make so many commits. 

Thanks,

Justin

**Comment by jentjr** [comment]
I'll see if I can get the conda-recipe to work for submittal to conda-forge.

**Comment by mbakker7** [comment]
Thanks for all the hard work, Justin.

This PR keeps on going and expanding and it is hard to decide when it is ready. 

It seems to me the Travis/Appveyor part is ready to go. Can you submit a separate pull request for that so I can include it? 

Then the second part: How is the conda build part going? I am especially interested in the windows part, as that is still where most users are (although I work on a Mac).

Thanks again,

Mark

**Comment by jentjr** [comment]
Mark,

The Travis/Appveyor builds are ready to go, and work for Python 3.5, 3.6, and 3.7. I will figure out how to submit that as a separate pull request.

The conda builds are working on windows and linux for me, and I've uploaded the files to my channel [https://anaconda.org/jentjr/timml/files](). I removed testing them on Travis/Appveyor though because the builds did not seem to work consistently. If you look back at the logs the conda build will work for one commit and then on the next commit the conda build breaks even though nothing was changed to the build recipe. I figured conda-forge is the place the test the conda build process anyways. 

I can submit a pull request to your fork of the conda-forge/stage-recipes, but I think for it to work the tagged version will need to incorporate my setup.py file and have besselaesnew.f95 in the timml/timml/src directory.  

Version 3 of conda build uses the new jinja2 compiler feature [https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html](url). For Mac the SDK needs to be available, but I think the conda-forge build process takes care of this in the the global conda_build_config.yaml [https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml](), so by specifying {{ compiler('fortran') }} in the build section of the meta.yaml file the right compiler should be found for linux, osx, and windows. 

Thanks for reviewing the PR. 

Justin

**Pull request closed without merging**
