### PR TITLE
Improved tracing metadata

### PR DESCRIPTION
**Pull request by Hugovdberg**
Currently the termination condition for the traces is not returned from the tracefunctions, and in various cases the printed message is not helpful either. Also, to plot the trace and get the actual trace takes two runs of the same traces.

This set of changes boils down to the following:
1) A fourth return value was added to the `changetrace` functions of the elements. This allows to return a message when the `changetrace` function causes termination of the trace. This has been added to all places where a `changetrace` function is defined, and where it is called. 
2) An `else` clause was added to the trace iterations. This is entered when the loop doesn't end by a `break` keyword. See also [this page](http://book.pythontips.com/en/latest/for_-_else.html). This adds an explicit message that the maximum number of iterations was reached before a termination condition was hit.
3) The return type of the `timtraceline` function was changed to a dictionary to allow for returning metadata on the tracing. In this implementation it contains the keys `trace` (the original return array of the traced points), `message` (the termination condition), `complete` (a boolean whether the trace terminated other then by the max iterations), and optionally `layers` (the list of layers for each traced point).
4) An argument called `return_traces` was added to the `tracelines` method of the `PlotTim` class. It defaults to `False`, but if it is set to `True` the traces are stored and returned at the end. If it is set to `False` the traces are not stored to prevent potential memory issues.

### CODE REVIEW

**Comment by mbakker7** [comment]
This is a good idea. Can you add a simple notebook example where all the different messages are shown: reach well, reached tmax, reached window boundary, etc? I suggest a simple model with 1 well, one line-sink and a few other things maybe.

**Comment by Hugovdberg** [comment]
@mbakker7 did you get around to checking out this pull request? 

I can imagine the changed return type of the `timtracelines` function is an obstacle to merging this, if you want to I can change it to return the old list by default, with the following upgrade plan:

1. Implement optional metadata in current version, by adding a `metadata=False` argument to `timtracelines`. Add a `FutureWarning` that the default behaviour will change in a future version
2. In a next version change the default value of `metadata` to `True`
3. In the next version after that add a `DeprecationWarning` that the option will be removed
4. Finally remove the `metadata` argument and just implement the new behaviour.

That way users are well prepared that the behaviour wil change, and can upgrade their models accordingly.

**Comment by Hugovdberg** [comment]
@mbakker7 oops, I started the previous message this morning, but only just got around to finishing the upgrade plan. I will create a notebook to show the functionality.

**Comment by mbakker7** [comment]
I prefer the FutureWarning option. Can you add that as well?

**Comment by mbakker7** [comment]
Oops, sounds like you already implemented the FutureWarning.
Let me know when you add an example Notebook and I will review.

**Comment by Hugovdberg** [comment]
I haven't implemented this upgrade plan yet, but I think it's the responsible way. I will add it, together with a notebook showing the options.

**Comment by mbakker7** [comment]
I think this is ready to be merged. Maybe needs a few small tweaks after additional testing.

**Pull request merged**
